/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DocumentType = { 'votersID' : null } |
  { 'passport' : null } |
  { 'nationalID' : null } |
  { 'driversLicense' : null };
export type ExternalBlob = Uint8Array;
export interface GiftCardRate {
  'id' : GiftCardRateId,
  'status' : GiftCardRateStatus,
  'createdAt' : Time,
  'updatedAt' : Time,
  'ratePercentage' : bigint,
  'brandName' : string,
}
export type GiftCardRateId = bigint;
export type GiftCardRateStatus = { 'active' : null } |
  { 'inactive' : null };
export interface KycRecord {
  'id' : KycRecordId,
  'status' : KycStatus,
  'documentType' : DocumentType,
  'signature' : [] | [ExternalBlob],
  'documentURI' : string,
  'user' : Principal,
  'submittedAt' : Time,
  'idNumber' : string,
  'verifiedAt' : [] | [Time],
}
export type KycRecordId = bigint;
export type KycStatus = { 'verified' : null } |
  { 'expired' : null } |
  { 'pending' : null } |
  { 'unverified' : null } |
  { 'rejected' : null };
export interface PayoutMethod {
  'id' : PayoutMethodId,
  'created' : Time,
  'owner' : Principal,
  'bankName' : string,
  'accountName' : string,
  'accountNumber' : string,
}
export type PayoutMethodId = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WithdrawalRequest {
  'id' : WithdrawalRequestId,
  'status' : WithdrawalStatus,
  'created' : Time,
  'payoutMethodId' : PayoutMethodId,
  'owner' : Principal,
  'processedAt' : [] | [Time],
  'processedBy' : [] | [Principal],
  'amount' : bigint,
}
export type WithdrawalRequestId = bigint;
export type WithdrawalStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'rejected' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGiftCardRate' : ActorMethod<[string, bigint], GiftCardRateId>,
  'createPayoutMethod' : ActorMethod<[string, string, string], PayoutMethodId>,
  'createWithdrawalRequest' : ActorMethod<
    [PayoutMethodId, bigint],
    WithdrawalRequestId
  >,
  'getActiveRateForBrand' : ActorMethod<[string], [] | [bigint]>,
  'getAllRates' : ActorMethod<[], Array<GiftCardRate>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getKycStatus' : ActorMethod<[], Array<KycRecord>>,
  'getUserKycRecords' : ActorMethod<[Principal], Array<KycRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActiveRates' : ActorMethod<[], Array<GiftCardRate>>,
  'listPendingWithdrawals' : ActorMethod<[], Array<WithdrawalRequest>>,
  'listUserPayoutMethods' : ActorMethod<[], Array<PayoutMethod>>,
  'listUserWithdrawals' : ActorMethod<[], Array<WithdrawalRequest>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setGiftCardRateStatus' : ActorMethod<
    [GiftCardRateId, { 'active' : null } | { 'inactive' : null }],
    undefined
  >,
  'submitKycRecord' : ActorMethod<
    [DocumentType, string, string, [] | [ExternalBlob]],
    KycRecordId
  >,
  'updateGiftCardRate' : ActorMethod<[GiftCardRateId, bigint], undefined>,
  'updateKycStatus' : ActorMethod<[KycRecordId, KycStatus], undefined>,
  'updateWithdrawalStatus' : ActorMethod<
    [WithdrawalRequestId, WithdrawalStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];