/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EscrowId = IDL.Nat;
export const ChatId = IDL.Nat;
export const GiftCardRateId = IDL.Nat;
export const PayoutMethodId = IDL.Nat;
export const WithdrawalRequestId = IDL.Nat;
export const Time = IDL.Int;
export const RateQuote = IDL.Record({
  'id' : IDL.Nat,
  'effectiveRate' : IDL.Nat,
  'coinPriceIndex' : IDL.Int,
  'createdAt' : Time,
  'ratePercentage' : IDL.Nat,
  'brandName' : IDL.Text,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'chatId' : ChatId,
});
export const GiftCardRateStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const GiftCardRate = IDL.Record({
  'id' : GiftCardRateId,
  'status' : GiftCardRateStatus,
  'createdAt' : Time,
  'updatedAt' : Time,
  'ratePercentage' : IDL.Nat,
  'brandName' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const KycRecordId = IDL.Nat;
export const KycStatus = IDL.Variant({
  'verified' : IDL.Null,
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'unverified' : IDL.Null,
  'rejected' : IDL.Null,
});
export const DocumentType = IDL.Variant({
  'votersID' : IDL.Null,
  'passport' : IDL.Null,
  'nationalID' : IDL.Null,
  'driversLicense' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const KycRecord = IDL.Record({
  'id' : KycRecordId,
  'status' : KycStatus,
  'documentType' : DocumentType,
  'signature' : IDL.Opt(ExternalBlob),
  'documentURI' : IDL.Text,
  'user' : IDL.Principal,
  'submittedAt' : Time,
  'idNumber' : IDL.Text,
  'verifiedAt' : IDL.Opt(Time),
});
export const WithdrawalConfig = IDL.Record({
  'minTimeToPaidStatus' : Time,
  'maxTimeToPaidStatus' : Time,
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'rejected' : IDL.Null,
});
export const WithdrawalRequest = IDL.Record({
  'id' : WithdrawalRequestId,
  'status' : WithdrawalStatus,
  'created' : Time,
  'payoutMethodId' : PayoutMethodId,
  'owner' : IDL.Principal,
  'processedAt' : IDL.Opt(Time),
  'processedBy' : IDL.Opt(IDL.Principal),
  'amount' : IDL.Nat,
});
export const PayoutMethod = IDL.Record({
  'id' : PayoutMethodId,
  'created' : Time,
  'owner' : IDL.Principal,
  'bankName' : IDL.Text,
  'accountName' : IDL.Text,
  'accountNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculatePayout' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'cancelEscrow' : IDL.Func([EscrowId], [], []),
  'createChat' : IDL.Func([IDL.Principal], [ChatId], []),
  'createEscrow' : IDL.Func([ChatId, IDL.Nat, IDL.Principal], [EscrowId], []),
  'createGiftCardRate' : IDL.Func([IDL.Text, IDL.Nat], [GiftCardRateId], []),
  'createPayoutMethod' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [PayoutMethodId],
      [],
    ),
  'createWithdrawalRequest' : IDL.Func(
      [PayoutMethodId, IDL.Nat],
      [WithdrawalRequestId],
      [],
    ),
  'fundEscrow' : IDL.Func([EscrowId], [], []),
  'generateRateQuote' : IDL.Func([IDL.Text, IDL.Nat], [RateQuote], []),
  'getActiveRateForBrand' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Int)], ['query']),
  'getAllChatMessages' : IDL.Func([ChatId], [IDL.Vec(Message)], []),
  'getAllRates' : IDL.Func([], [IDL.Vec(GiftCardRate)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoinPriceIndex' : IDL.Func([], [IDL.Int], ['query']),
  'getCryptoStarIndex' : IDL.Func([], [IDL.Int], ['query']),
  'getKycStatus' : IDL.Func([], [IDL.Vec(KycRecord)], ['query']),
  'getUserKycRecords' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(KycRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWithdrawalConfig' : IDL.Func([], [WithdrawalConfig], ['query']),
  'hasVerifiedTraderBadge' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerKycVerified' : IDL.Func([], [IDL.Bool], ['query']),
  'listActiveRates' : IDL.Func([], [IDL.Vec(GiftCardRate)], ['query']),
  'listPendingWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalRequest)], []),
  'listUserPayoutMethods' : IDL.Func([], [IDL.Vec(PayoutMethod)], ['query']),
  'listUserWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalRequest)], ['query']),
  'releaseEscrow' : IDL.Func([EscrowId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([ChatId, IDL.Text], [], []),
  'setCoinPriceIndex' : IDL.Func([IDL.Int], [], []),
  'setGiftCardRateStatus' : IDL.Func(
      [
        GiftCardRateId,
        IDL.Variant({ 'active' : IDL.Null, 'inactive' : IDL.Null }),
      ],
      [],
      [],
    ),
  'setWithdrawalConfig' : IDL.Func([Time, Time], [], []),
  'submitKycRecord' : IDL.Func(
      [DocumentType, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [KycRecordId],
      [],
    ),
  'updateGiftCardRate' : IDL.Func([GiftCardRateId, IDL.Nat], [], []),
  'updateKycStatus' : IDL.Func([KycRecordId, KycStatus], [], []),
  'updateWithdrawalStatus' : IDL.Func(
      [WithdrawalRequestId, WithdrawalStatus],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EscrowId = IDL.Nat;
  const ChatId = IDL.Nat;
  const GiftCardRateId = IDL.Nat;
  const PayoutMethodId = IDL.Nat;
  const WithdrawalRequestId = IDL.Nat;
  const Time = IDL.Int;
  const RateQuote = IDL.Record({
    'id' : IDL.Nat,
    'effectiveRate' : IDL.Nat,
    'coinPriceIndex' : IDL.Int,
    'createdAt' : Time,
    'ratePercentage' : IDL.Nat,
    'brandName' : IDL.Text,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'chatId' : ChatId,
  });
  const GiftCardRateStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const GiftCardRate = IDL.Record({
    'id' : GiftCardRateId,
    'status' : GiftCardRateStatus,
    'createdAt' : Time,
    'updatedAt' : Time,
    'ratePercentage' : IDL.Nat,
    'brandName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const KycRecordId = IDL.Nat;
  const KycStatus = IDL.Variant({
    'verified' : IDL.Null,
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'unverified' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const DocumentType = IDL.Variant({
    'votersID' : IDL.Null,
    'passport' : IDL.Null,
    'nationalID' : IDL.Null,
    'driversLicense' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const KycRecord = IDL.Record({
    'id' : KycRecordId,
    'status' : KycStatus,
    'documentType' : DocumentType,
    'signature' : IDL.Opt(ExternalBlob),
    'documentURI' : IDL.Text,
    'user' : IDL.Principal,
    'submittedAt' : Time,
    'idNumber' : IDL.Text,
    'verifiedAt' : IDL.Opt(Time),
  });
  const WithdrawalConfig = IDL.Record({
    'minTimeToPaidStatus' : Time,
    'maxTimeToPaidStatus' : Time,
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const WithdrawalRequest = IDL.Record({
    'id' : WithdrawalRequestId,
    'status' : WithdrawalStatus,
    'created' : Time,
    'payoutMethodId' : PayoutMethodId,
    'owner' : IDL.Principal,
    'processedAt' : IDL.Opt(Time),
    'processedBy' : IDL.Opt(IDL.Principal),
    'amount' : IDL.Nat,
  });
  const PayoutMethod = IDL.Record({
    'id' : PayoutMethodId,
    'created' : Time,
    'owner' : IDL.Principal,
    'bankName' : IDL.Text,
    'accountName' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculatePayout' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'cancelEscrow' : IDL.Func([EscrowId], [], []),
    'createChat' : IDL.Func([IDL.Principal], [ChatId], []),
    'createEscrow' : IDL.Func([ChatId, IDL.Nat, IDL.Principal], [EscrowId], []),
    'createGiftCardRate' : IDL.Func([IDL.Text, IDL.Nat], [GiftCardRateId], []),
    'createPayoutMethod' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [PayoutMethodId],
        [],
      ),
    'createWithdrawalRequest' : IDL.Func(
        [PayoutMethodId, IDL.Nat],
        [WithdrawalRequestId],
        [],
      ),
    'fundEscrow' : IDL.Func([EscrowId], [], []),
    'generateRateQuote' : IDL.Func([IDL.Text, IDL.Nat], [RateQuote], []),
    'getActiveRateForBrand' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Int)],
        ['query'],
      ),
    'getAllChatMessages' : IDL.Func([ChatId], [IDL.Vec(Message)], []),
    'getAllRates' : IDL.Func([], [IDL.Vec(GiftCardRate)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoinPriceIndex' : IDL.Func([], [IDL.Int], ['query']),
    'getCryptoStarIndex' : IDL.Func([], [IDL.Int], ['query']),
    'getKycStatus' : IDL.Func([], [IDL.Vec(KycRecord)], ['query']),
    'getUserKycRecords' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(KycRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWithdrawalConfig' : IDL.Func([], [WithdrawalConfig], ['query']),
    'hasVerifiedTraderBadge' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerKycVerified' : IDL.Func([], [IDL.Bool], ['query']),
    'listActiveRates' : IDL.Func([], [IDL.Vec(GiftCardRate)], ['query']),
    'listPendingWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalRequest)], []),
    'listUserPayoutMethods' : IDL.Func([], [IDL.Vec(PayoutMethod)], ['query']),
    'listUserWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'releaseEscrow' : IDL.Func([EscrowId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([ChatId, IDL.Text], [], []),
    'setCoinPriceIndex' : IDL.Func([IDL.Int], [], []),
    'setGiftCardRateStatus' : IDL.Func(
        [
          GiftCardRateId,
          IDL.Variant({ 'active' : IDL.Null, 'inactive' : IDL.Null }),
        ],
        [],
        [],
      ),
    'setWithdrawalConfig' : IDL.Func([Time, Time], [], []),
    'submitKycRecord' : IDL.Func(
        [DocumentType, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [KycRecordId],
        [],
      ),
    'updateGiftCardRate' : IDL.Func([GiftCardRateId, IDL.Nat], [], []),
    'updateKycStatus' : IDL.Func([KycRecordId, KycStatus], [], []),
    'updateWithdrawalStatus' : IDL.Func(
        [WithdrawalRequestId, WithdrawalStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };