/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type KycRecordId = bigint;
export type Time = bigint;
export type WithdrawalRequestId = bigint;
export type PayoutMethodId = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type GiftCardRateId = bigint;
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PayoutMethod {
    id: PayoutMethodId;
    created: Time;
    owner: Principal;
    bankName: string;
    accountName: string;
    accountNumber: string;
}
export interface KycRecord {
    id: KycRecordId;
    status: KycStatus;
    documentType: DocumentType;
    signature?: ExternalBlob;
    documentURI: string;
    user: Principal;
    submittedAt: Time;
    idNumber: string;
    verifiedAt?: Time;
}
export interface GiftCardRate {
    id: GiftCardRateId;
    status: GiftCardRateStatus;
    createdAt: Time;
    updatedAt: Time;
    ratePercentage: bigint;
    brandName: string;
}
export interface WithdrawalRequest {
    id: WithdrawalRequestId;
    status: WithdrawalStatus;
    created: Time;
    payoutMethodId: PayoutMethodId;
    owner: Principal;
    processedAt?: Time;
    processedBy?: Principal;
    amount: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
}
export enum DocumentType {
    votersID = "votersID",
    passport = "passport",
    nationalID = "nationalID",
    driversLicense = "driversLicense"
}
export enum GiftCardRateStatus {
    active = "active",
    inactive = "inactive"
}
export enum KycStatus {
    verified = "verified",
    expired = "expired",
    pending = "pending",
    unverified = "unverified",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WithdrawalStatus {
    pending = "pending",
    paid = "paid",
    rejected = "rejected"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createGiftCardRate(brandName: string, ratePercentage: bigint): Promise<GiftCardRateId>;
    createPayoutMethod(bankName: string, accountNumber: string, accountName: string): Promise<PayoutMethodId>;
    createWithdrawalRequest(payoutMethodId: PayoutMethodId, amount: bigint): Promise<WithdrawalRequestId>;
    getActiveRateForBrand(brandName: string): Promise<bigint | null>;
    getAllRates(): Promise<Array<GiftCardRate>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getKycStatus(): Promise<Array<KycRecord>>;
    getUserKycRecords(user: Principal): Promise<Array<KycRecord>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listActiveRates(): Promise<Array<GiftCardRate>>;
    listPendingWithdrawals(): Promise<Array<WithdrawalRequest>>;
    listUserPayoutMethods(): Promise<Array<PayoutMethod>>;
    listUserWithdrawals(): Promise<Array<WithdrawalRequest>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setGiftCardRateStatus(rateId: GiftCardRateId, status: GiftCardRateStatus): Promise<void>;
    submitKycRecord(documentType: DocumentType, idNumber: string, documentURI: string, signature: ExternalBlob | null): Promise<KycRecordId>;
    updateGiftCardRate(rateId: GiftCardRateId, ratePercentage: bigint): Promise<void>;
    updateKycStatus(recordId: KycRecordId, status: KycStatus): Promise<void>;
    updateWithdrawalStatus(requestId: WithdrawalRequestId, status: WithdrawalStatus): Promise<void>;
}
import type { DocumentType as _DocumentType, ExternalBlob as _ExternalBlob, GiftCardRate as _GiftCardRate, GiftCardRateId as _GiftCardRateId, GiftCardRateStatus as _GiftCardRateStatus, KycRecord as _KycRecord, KycRecordId as _KycRecordId, KycStatus as _KycStatus, PayoutMethodId as _PayoutMethodId, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, WithdrawalRequest as _WithdrawalRequest, WithdrawalRequestId as _WithdrawalRequestId, WithdrawalStatus as _WithdrawalStatus, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createGiftCardRate(arg0: string, arg1: bigint): Promise<GiftCardRateId> {
        if (this.processError) {
            try {
                const result = await this.actor.createGiftCardRate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGiftCardRate(arg0, arg1);
            return result;
        }
    }
    async createPayoutMethod(arg0: string, arg1: string, arg2: string): Promise<PayoutMethodId> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayoutMethod(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayoutMethod(arg0, arg1, arg2);
            return result;
        }
    }
    async createWithdrawalRequest(arg0: PayoutMethodId, arg1: bigint): Promise<WithdrawalRequestId> {
        if (this.processError) {
            try {
                const result = await this.actor.createWithdrawalRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWithdrawalRequest(arg0, arg1);
            return result;
        }
    }
    async getActiveRateForBrand(arg0: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveRateForBrand(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveRateForBrand(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRates(): Promise<Array<GiftCardRate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRates();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRates();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKycStatus(): Promise<Array<KycRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getKycStatus();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKycStatus();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserKycRecords(arg0: Principal): Promise<Array<KycRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserKycRecords(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserKycRecords(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listActiveRates(): Promise<Array<GiftCardRate>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActiveRates();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActiveRates();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPendingWithdrawals(): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingWithdrawals();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingWithdrawals();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUserPayoutMethods(): Promise<Array<PayoutMethod>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUserPayoutMethods();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUserPayoutMethods();
            return result;
        }
    }
    async listUserWithdrawals(): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUserWithdrawals();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUserWithdrawals();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setGiftCardRateStatus(arg0: GiftCardRateId, arg1: GiftCardRateStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGiftCardRateStatus(arg0, to_candid_variant_n34(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGiftCardRateStatus(arg0, to_candid_variant_n34(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitKycRecord(arg0: DocumentType, arg1: string, arg2: string, arg3: ExternalBlob | null): Promise<KycRecordId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitKycRecord(to_candid_DocumentType_n35(this._uploadFile, this._downloadFile, arg0), arg1, arg2, await to_candid_opt_n37(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitKycRecord(to_candid_DocumentType_n35(this._uploadFile, this._downloadFile, arg0), arg1, arg2, await to_candid_opt_n37(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateGiftCardRate(arg0: GiftCardRateId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGiftCardRate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGiftCardRate(arg0, arg1);
            return result;
        }
    }
    async updateKycStatus(arg0: KycRecordId, arg1: KycStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateKycStatus(arg0, to_candid_KycStatus_n39(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateKycStatus(arg0, to_candid_KycStatus_n39(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateWithdrawalStatus(arg0: WithdrawalRequestId, arg1: WithdrawalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWithdrawalStatus(arg0, to_candid_WithdrawalStatus_n41(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWithdrawalStatus(arg0, to_candid_WithdrawalStatus_n41(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_DocumentType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentType): DocumentType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_GiftCardRateStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GiftCardRateStatus): GiftCardRateStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_GiftCardRate_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GiftCardRate): GiftCardRate {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function from_candid_KycRecord_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KycRecord): Promise<KycRecord> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_KycStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KycStatus): KycStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalRequest_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalRequest): WithdrawalRequest {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalStatus): WithdrawalStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _GiftCardRateId;
    status: _GiftCardRateStatus;
    createdAt: _Time;
    updatedAt: _Time;
    ratePercentage: bigint;
    brandName: string;
}): {
    id: GiftCardRateId;
    status: GiftCardRateStatus;
    createdAt: Time;
    updatedAt: Time;
    ratePercentage: bigint;
    brandName: string;
} {
    return {
        id: value.id,
        status: from_candid_GiftCardRateStatus_n13(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        ratePercentage: value.ratePercentage,
        brandName: value.brandName
    };
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _KycRecordId;
    status: _KycStatus;
    documentType: _DocumentType;
    signature: [] | [_ExternalBlob];
    documentURI: string;
    user: Principal;
    submittedAt: _Time;
    idNumber: string;
    verifiedAt: [] | [_Time];
}): Promise<{
    id: KycRecordId;
    status: KycStatus;
    documentType: DocumentType;
    signature?: ExternalBlob;
    documentURI: string;
    user: Principal;
    submittedAt: Time;
    idNumber: string;
    verifiedAt?: Time;
}> {
    return {
        id: value.id,
        status: from_candid_KycStatus_n21(_uploadFile, _downloadFile, value.status),
        documentType: from_candid_DocumentType_n23(_uploadFile, _downloadFile, value.documentType),
        signature: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.signature)),
        documentURI: value.documentURI,
        user: value.user,
        submittedAt: value.submittedAt,
        idNumber: value.idNumber,
        verifiedAt: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.verifiedAt))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _WithdrawalRequestId;
    status: _WithdrawalStatus;
    created: _Time;
    payoutMethodId: _PayoutMethodId;
    owner: Principal;
    processedAt: [] | [_Time];
    processedBy: [] | [Principal];
    amount: bigint;
}): {
    id: WithdrawalRequestId;
    status: WithdrawalStatus;
    created: Time;
    payoutMethodId: PayoutMethodId;
    owner: Principal;
    processedAt?: Time;
    processedBy?: Principal;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_WithdrawalStatus_n31(_uploadFile, _downloadFile, value.status),
        created: value.created,
        payoutMethodId: value.payoutMethodId,
        owner: value.owner,
        processedAt: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.processedAt)),
        processedBy: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.processedBy)),
        amount: value.amount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): GiftCardRateStatus {
    return "active" in value ? GiftCardRateStatus.active : "inactive" in value ? GiftCardRateStatus.inactive : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    expired: null;
} | {
    pending: null;
} | {
    unverified: null;
} | {
    rejected: null;
}): KycStatus {
    return "verified" in value ? KycStatus.verified : "expired" in value ? KycStatus.expired : "pending" in value ? KycStatus.pending : "unverified" in value ? KycStatus.unverified : "rejected" in value ? KycStatus.rejected : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    votersID: null;
} | {
    passport: null;
} | {
    nationalID: null;
} | {
    driversLicense: null;
}): DocumentType {
    return "votersID" in value ? DocumentType.votersID : "passport" in value ? DocumentType.passport : "nationalID" in value ? DocumentType.nationalID : "driversLicense" in value ? DocumentType.driversLicense : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    rejected: null;
}): WithdrawalStatus {
    return "pending" in value ? WithdrawalStatus.pending : "paid" in value ? WithdrawalStatus.paid : "rejected" in value ? WithdrawalStatus.rejected : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GiftCardRate>): Array<GiftCardRate> {
    return value.map((x)=>from_candid_GiftCardRate_n11(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_KycRecord>): Promise<Array<KycRecord>> {
    return await Promise.all(value.map(async (x)=>await from_candid_KycRecord_n19(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalRequest>): Array<WithdrawalRequest> {
    return value.map((x)=>from_candid_WithdrawalRequest_n29(_uploadFile, _downloadFile, x));
}
function to_candid_DocumentType_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentType): _DocumentType {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_KycStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KycStatus): _KycStatus {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_WithdrawalStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WithdrawalStatus): _WithdrawalStatus {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n38(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GiftCardRateStatus): {
    active: null;
} | {
    inactive: null;
} {
    return value == GiftCardRateStatus.active ? {
        active: null
    } : value == GiftCardRateStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentType): {
    votersID: null;
} | {
    passport: null;
} | {
    nationalID: null;
} | {
    driversLicense: null;
} {
    return value == DocumentType.votersID ? {
        votersID: null
    } : value == DocumentType.passport ? {
        passport: null
    } : value == DocumentType.nationalID ? {
        nationalID: null
    } : value == DocumentType.driversLicense ? {
        driversLicense: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KycStatus): {
    verified: null;
} | {
    expired: null;
} | {
    pending: null;
} | {
    unverified: null;
} | {
    rejected: null;
} {
    return value == KycStatus.verified ? {
        verified: null
    } : value == KycStatus.expired ? {
        expired: null
    } : value == KycStatus.pending ? {
        pending: null
    } : value == KycStatus.unverified ? {
        unverified: null
    } : value == KycStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WithdrawalStatus): {
    pending: null;
} | {
    paid: null;
} | {
    rejected: null;
} {
    return value == WithdrawalStatus.pending ? {
        pending: null
    } : value == WithdrawalStatus.paid ? {
        paid: null
    } : value == WithdrawalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
